
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=oracledb
      - DB_PORT=1521
      - DB_USER=system
      - DB_PASSWORD=oraclepassword
    depends_on:
      - api_usuario
      - api_contenidos
      - api_visualizaciones
      - oracledb
    networks:
      - app-network

  api_usuario:
    build:
      context: ./API_Usuario
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=swagger_server.__main__.py
    networks:
      - app-network

  api_contenidos:
    build:
      context: ./API_Contenidos
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=swagger_server.__main__.py
    networks:
      - app-network

  api_visualizaciones:
    build:
      context: ./API_Visualizaciones
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=swagger_server.__main__.py
    networks:
      - app-network
  
  oracledb:
    image: oraclelinux:7-slim
    container_name: datebase
    ports: 
      - "1522:1521"
      - "5500:5500"
    environment:
      - ORACLE_HOME=/opt/oracle/product/21c/dbhome_1 
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PASSWORD=oraclepassword
    volumes:
      - oracle-data:/u01/app/oracle # Volumen persistente para los datos de Oracle
      - data-pump-dir:/u01/app/oracle/product/19c/dbhome_1/data_pump_dir # Volumen persistente para Data Pump
    networks:
      - app-network
    command: >
      bash -c "/u01/app/oracle/product/19c/dbhome_1/bin/lsnrctl start && tail -f /dev/null"

  

  web:
    build: .
    ports:
      - "80:80"  # Apache servir치 archivos est치ticos en el puerto 80
      - "5004:5000"  # La API de Python se ejecutar치 en el puerto 5000
    volumes:
      - ./static:/var/www/html/static  # Volumen para los archivos est치ticos
      - ./templates:/var/www/html  # Volumen para los templates
      - ./app.py:/app/app.py  # Volumen para el archivo principal
      - ./:/app


networks:
  app-network:
    driver: bridge
   
volumes:
  oracle-data:
    driver: local
  data-pump-dir:  # Volumen para el directorio de Data Pump
    driver: local


  

