# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class VisualizacionesSeries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, serie_id: str=None, num_visualizaciones: int=None):  # noqa: E501
        """VisualizacionesSeries - a model defined in Swagger

        :param id: The id of this VisualizacionesSeries.  # noqa: E501
        :type id: str
        :param serie_id: The serie_id of this VisualizacionesSeries.  # noqa: E501
        :type serie_id: str
        :param num_visualizaciones: The num_visualizaciones of this VisualizacionesSeries.  # noqa: E501
        :type num_visualizaciones: int
        """
        self.swagger_types = {
            'id': str,
            'serie_id': str,
            'num_visualizaciones': int
        }

        self.attribute_map = {
            'id': 'id',
            'serie_id': 'serieId',
            'num_visualizaciones': 'numVisualizaciones'
        }
        self._id = id
        self._serie_id = serie_id
        self._num_visualizaciones = num_visualizaciones

    @classmethod
    def from_dict(cls, dikt) -> 'VisualizacionesSeries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The visualizacionesSeries of this VisualizacionesSeries.  # noqa: E501
        :rtype: VisualizacionesSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this VisualizacionesSeries.


        :return: The id of this VisualizacionesSeries.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this VisualizacionesSeries.


        :param id: The id of this VisualizacionesSeries.
        :type id: str
        """

        self._id = id

    @property
    def serie_id(self) -> str:
        """Gets the serie_id of this VisualizacionesSeries.


        :return: The serie_id of this VisualizacionesSeries.
        :rtype: str
        """
        return self._serie_id

    @serie_id.setter
    def serie_id(self, serie_id: str):
        """Sets the serie_id of this VisualizacionesSeries.


        :param serie_id: The serie_id of this VisualizacionesSeries.
        :type serie_id: str
        """

        self._serie_id = serie_id

    @property
    def num_visualizaciones(self) -> int:
        """Gets the num_visualizaciones of this VisualizacionesSeries.


        :return: The num_visualizaciones of this VisualizacionesSeries.
        :rtype: int
        """
        return self._num_visualizaciones

    @num_visualizaciones.setter
    def num_visualizaciones(self, num_visualizaciones: int):
        """Sets the num_visualizaciones of this VisualizacionesSeries.


        :param num_visualizaciones: The num_visualizaciones of this VisualizacionesSeries.
        :type num_visualizaciones: int
        """

        self._num_visualizaciones = num_visualizaciones
