# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from ..models.director import Director  # noqa: F401,E501
from .. import util


class Capitulo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, titulo: str=None, num_capitulo: int=None, descripcion: str=None, duracion: str=None, director: Director=None):  # noqa: E501
        """Capitulo - a model defined in Swagger

        :param id: The id of this Capitulo.  # noqa: E501
        :type id: str
        :param titulo: The titulo of this Capitulo.  # noqa: E501
        :type titulo: str
        :param num_capitulo: The num_capitulo of this Capitulo.  # noqa: E501
        :type num_capitulo: int
        :param descripcion: The descripcion of this Capitulo.  # noqa: E501
        :type descripcion: str
        :param duracion: The duracion of this Capitulo.  # noqa: E501
        :type duracion: str
        :param director: The director of this Capitulo.  # noqa: E501
        :type director: Director
        """
        self.swagger_types = {
            'id': str,
            'titulo': str,
            'num_capitulo': int,
            'descripcion': str,
            'duracion': str,
            'director': Director
        }

        self.attribute_map = {
            'id': 'id',
            'titulo': 'titulo',
            'num_capitulo': 'numCapitulo',
            'descripcion': 'descripcion',
            'duracion': 'duracion',
            'director': 'director'
        }
        self._id = id
        self._titulo = titulo
        self._num_capitulo = num_capitulo
        self._descripcion = descripcion
        self._duracion = duracion
        self._director = director

    @classmethod
    def from_dict(cls, dikt) -> 'Capitulo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Capitulo of this Capitulo.  # noqa: E501
        :rtype: Capitulo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Capitulo.


        :return: The id of this Capitulo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Capitulo.


        :param id: The id of this Capitulo.
        :type id: str
        """

        self._id = id

    @property
    def titulo(self) -> str:
        """Gets the titulo of this Capitulo.


        :return: The titulo of this Capitulo.
        :rtype: str
        """
        return self._titulo

    @titulo.setter
    def titulo(self, titulo: str):
        """Sets the titulo of this Capitulo.


        :param titulo: The titulo of this Capitulo.
        :type titulo: str
        """

        self._titulo = titulo

    @property
    def num_capitulo(self) -> int:
        """Gets the num_capitulo of this Capitulo.


        :return: The num_capitulo of this Capitulo.
        :rtype: int
        """
        return self._num_capitulo

    @num_capitulo.setter
    def num_capitulo(self, num_capitulo: int):
        """Sets the num_capitulo of this Capitulo.


        :param num_capitulo: The num_capitulo of this Capitulo.
        :type num_capitulo: int
        """

        self._num_capitulo = num_capitulo

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Capitulo.


        :return: The descripcion of this Capitulo.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Capitulo.


        :param descripcion: The descripcion of this Capitulo.
        :type descripcion: str
        """

        self._descripcion = descripcion

    @property
    def duracion(self) -> str:
        """Gets the duracion of this Capitulo.


        :return: The duracion of this Capitulo.
        :rtype: str
        """
        return self._duracion

    @duracion.setter
    def duracion(self, duracion: str):
        """Sets the duracion of this Capitulo.


        :param duracion: The duracion of this Capitulo.
        :type duracion: str
        """

        self._duracion = duracion

    @property
    def director(self) -> Director:
        """Gets the director of this Capitulo.


        :return: The director of this Capitulo.
        :rtype: Director
        """
        return self._director

    @director.setter
    def director(self, director: Director):
        """Sets the director of this Capitulo.


        :param director: The director of this Capitulo.
        :type director: Director
        """

        self._director = director
