# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class RecomendacionesPeliculas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, usuario_id: int=None, recomendaciones: List[str]=None):  # noqa: E501
        """RecomendacionesPeliculas - a model defined in Swagger

        :param id: The id of this RecomendacionesPeliculas.  # noqa: E501
        :type id: str
        :param usuario_id: The usuario_id of this RecomendacionesPeliculas.  # noqa: E501
        :type usuario_id: int
        :param recomendaciones: The recomendaciones of this RecomendacionesPeliculas.  # noqa: E501
        :type recomendaciones: List[str]
        """
        self.swagger_types = {
            'id': str,
            'usuario_id': int,
            'recomendaciones': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'usuario_id': 'usuarioId',
            'recomendaciones': 'recomendaciones'
        }
        self._id = id
        self._usuario_id = usuario_id
        self._recomendaciones = recomendaciones

    @classmethod
    def from_dict(cls, dikt) -> 'RecomendacionesPeliculas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The recomendacionesPeliculas of this RecomendacionesPeliculas.  # noqa: E501
        :rtype: RecomendacionesPeliculas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this RecomendacionesPeliculas.


        :return: The id of this RecomendacionesPeliculas.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this RecomendacionesPeliculas.


        :param id: The id of this RecomendacionesPeliculas.
        :type id: str
        """

        self._id = id

    @property
    def usuario_id(self) -> int:
        """Gets the usuario_id of this RecomendacionesPeliculas.


        :return: The usuario_id of this RecomendacionesPeliculas.
        :rtype: int
        """
        return self._usuario_id

    @usuario_id.setter
    def usuario_id(self, usuario_id: int):
        """Sets the usuario_id of this RecomendacionesPeliculas.


        :param usuario_id: The usuario_id of this RecomendacionesPeliculas.
        :type usuario_id: int
        """

        self._usuario_id = usuario_id

    @property
    def recomendaciones(self) -> List[str]:
        """Gets the recomendaciones of this RecomendacionesPeliculas.


        :return: The recomendaciones of this RecomendacionesPeliculas.
        :rtype: List[str]
        """
        return self._recomendaciones

    @recomendaciones.setter
    def recomendaciones(self, recomendaciones: List[str]):
        """Sets the recomendaciones of this RecomendacionesPeliculas.


        :param recomendaciones: The recomendaciones of this RecomendacionesPeliculas.
        :type recomendaciones: List[str]
        """

        self._recomendaciones = recomendaciones
