# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class UsuariosIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nombre_completo: str=None):  # noqa: E501
        """UsuariosIdBody - a model defined in Swagger

        :param nombre_completo: The nombre_completo of this UsuariosIdBody.  # noqa: E501
        :type nombre_completo: str
        """
        self.swagger_types = {
            'nombre_completo': str
        }

        self.attribute_map = {
            'nombre_completo': 'nombre_completo'
        }
        self._nombre_completo = nombre_completo

    @classmethod
    def from_dict(cls, dikt) -> 'UsuariosIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The usuarios_id_body of this UsuariosIdBody.  # noqa: E501
        :rtype: UsuariosIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre_completo(self) -> str:
        """Gets the nombre_completo of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :return: The nombre_completo of this UsuariosIdBody.
        :rtype: str
        """
        return self._nombre_completo

    @nombre_completo.setter
    def nombre_completo(self, nombre_completo: str):
        """Sets the nombre_completo of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :param nombre_completo: The nombre_completo of this UsuariosIdBody.
        :type nombre_completo: str
        """

        self._nombre_completo = nombre_completo
