# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.API_Usuario.swagger_server.models.base_model_ import Model
from api.API_Usuario.swagger_server import util


class IdCorreoBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, correo: str=None):  # noqa: E501
        """IdCorreoBody - a model defined in Swagger

        :param correo: The correo of this IdCorreoBody.  # noqa: E501
        :type correo: str
        """
        self.swagger_types = {
            'correo': str
        }

        self.attribute_map = {
            'correo': 'correo'
        }
        self._correo = correo

    @classmethod
    def from_dict(cls, dikt) -> 'IdCorreoBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The id_correo_body of this IdCorreoBody.  # noqa: E501
        :rtype: IdCorreoBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def correo(self) -> str:
        """Gets the correo of this IdCorreoBody.

        Nuevo correo electrónico  # noqa: E501

        :return: The correo of this IdCorreoBody.
        :rtype: str
        """
        return self._correo

    @correo.setter
    def correo(self, correo: str):
        """Sets the correo of this IdCorreoBody.

        Nuevo correo electrónico  # noqa: E501

        :param correo: The correo of this IdCorreoBody.
        :type correo: str
        """

        self._correo = correo
