# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IdGenerosfavoritosBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, generos_favoritos: List[str]=None):  # noqa: E501
        """IdGenerosfavoritosBody - a model defined in Swagger

        :param generos_favoritos: The generos_favoritos of this IdGenerosfavoritosBody.  # noqa: E501
        :type generos_favoritos: List[str]
        """
        self.swagger_types = {
            'generos_favoritos': List[str]
        }

        self.attribute_map = {
            'generos_favoritos': 'generos_favoritos'
        }
        self._generos_favoritos = generos_favoritos

    @classmethod
    def from_dict(cls, dikt) -> 'IdGenerosfavoritosBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The id_generosfavoritos_body of this IdGenerosfavoritosBody.  # noqa: E501
        :rtype: IdGenerosfavoritosBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def generos_favoritos(self) -> List[str]:
        """Gets the generos_favoritos of this IdGenerosfavoritosBody.


        :return: The generos_favoritos of this IdGenerosfavoritosBody.
        :rtype: List[str]
        """
        return self._generos_favoritos

    @generos_favoritos.setter
    def generos_favoritos(self, generos_favoritos: List[str]):
        """Sets the generos_favoritos of this IdGenerosfavoritosBody.


        :param generos_favoritos: The generos_favoritos of this IdGenerosfavoritosBody.
        :type generos_favoritos: List[str]
        """

        self._generos_favoritos = generos_favoritos
