# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.API_Usuario.swagger_server.models.base_model_ import Model
from api.API_Usuario.swagger_server import util


class UsuariosIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nombre: str=None, apellidos: str=None):  # noqa: E501
        """UsuariosIdBody - a model defined in Swagger

        :param nombre: The nombre of this UsuariosIdBody.  # noqa: E501
        :type nombre: str
        :param apellidos: The apellidos of this UsuariosIdBody.  # noqa: E501
        :type apellidos: str
        """
        self.swagger_types = {
            'nombre': str,
            'apellidos': str
        }

        self.attribute_map = {
            'nombre': 'nombre',
            'apellidos': 'apellidos'
        }
        self._nombre = nombre
        self._apellidos = apellidos

    @classmethod
    def from_dict(cls, dikt) -> 'UsuariosIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The usuarios_id_body of this UsuariosIdBody.  # noqa: E501
        :rtype: UsuariosIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre(self) -> str:
        """Gets the nombre of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :return: The nombre of this UsuariosIdBody.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :param nombre: The nombre of this UsuariosIdBody.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def apellidos(self) -> str:
        """Gets the apellidos of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :return: The apellidos of this UsuariosIdBody.
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos: str):
        """Sets the apellidos of this UsuariosIdBody.

        Nuevo nombre completo del usuario  # noqa: E501

        :param apellidos: The apellidos of this UsuariosIdBody.
        :type apellidos: str
        """

        self._apellidos = apellidos
