#!/bin/sh
#
# $Header: install/utl/scripts/db/dbSetup.sh /main/2 2017/03/08 09:44:22 davjimen Exp $
#
# dbSetup.sh
#
# Copyright (c) 2016, 2017, Oracle and/or its affiliates. All rights reserved.
#
#    NAME
#      dbSetup.sh
#
#    DESCRIPTION
#      script to launch db setup wizard for configuring Database home image
#
#    MODIFIED   (MM/DD/YY)
#    davjimen    01/18/17 - change the launching command libraries
#    davjimen    09/27/16 - Creation
#
ORACLE_HOME="";

DIRNAME="/usr/bin/dirname";
UNAME="/bin/uname";
DIRLOC="`${DIRNAME} $0`";
if [ "`${UNAME}`" = "SunOS" ] && [ "`${UNAME} -r`" = "5.10" ]; then
  SYMLINKSFOUND="false";
  AUXDIRLOC="${DIRLOC}";
  while [ "${AUXDIRLOC}" != "." ] && [ "${AUXDIRLOC}" != "/" ]; do
    if [ -L "${AUXDIRLOC}" ]; then
      SYMLINKSFOUND="true";
      break;
    fi
    AUXDIRLOC="`${DIRNAME} ${AUXDIRLOC}`";
  done
 
  if [ "${SYMLINKSFOUND}" = "true" ]; then
    case "${DIRLOC}" in
      /*)
        ORACLE_HOME="${DIRLOC}";
      ;;
      *)
        CURRENTDIR="`pwd`";
        ORACLE_HOME="${CURRENTDIR}/${DIRLOC}";
      ;;
    esac
  else
    cd "${DIRLOC}";
    ORACLE_HOME="`pwd -L`";
  fi
else
  cd "${DIRLOC}";
  ORACLE_HOME="`pwd -L`";
fi

export ORACLE_HOME;

# Execute the common setup code
. ${ORACLE_HOME}/bin/commonSetup.sh $*;

unset module;

# Define CVU OS Settings
SHELL_NOFILE_SOFT_LIMIT="`/bin/sh -c 'ulimit -S -n'`";
SHELL_STACK_SOFT_LIMIT="`/bin/sh -c 'ulimit -S -s'`";
SHELL_UMASK="`/bin/sh -c 'umask'`";
CVU_OS_SETTINGS="CVU_OS_SETTINGS=SHELL_NOFILE_SOFT_LIMIT:${SHELL_NOFILE_SOFT_LIMIT},SHELL_STACK_SOFT_LIMIT:${SHELL_STACK_SOFT_LIMIT},SHELL_UMASK:${SHELL_UMASK}";

${ORACLE_HOME}/perl/bin/perl -I${ORACLE_HOME}/perl/lib -I${ORACLE_HOME}/bin ${ORACLE_HOME}/bin/dbSetup.pl -J-D${CVU_OS_SETTINGS} $*
exit $?
